### ISSUE TITLE
Example causes error AttributeError: 'NoneType' object has no attribute 'itemAt'

### ISSUE THREAD

**Issue by photodude** [lmzach09/PyQt_Photo_Album_Desktop_App#1]
Attempting to follow the example, I copied and pasted from the medium article and I get the following error in VSCode

```CLI
PS Python-Desktop-App>  ${env:PTVSD_LAUNCHER_PORT}='59489'; & 'C:\ProgramData\Anaconda3\python.exe' 'c:\Users\[user]\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher' 'Python-Desktop-App\app.py' 
Traceback (most recent call last):
  File "Python-Desktop-App\app.py", line 160, in <module>
    ex = App()
  File "Python-Desktop-App\app.py", line 134, in __init__
    display_image=self.display_image)
  File "Python-Desktop-App\app.py", line 100, in __init__
    self.on_thumbnail_click(None, 0, first_img_file_path)
  File "Python-Desktop-App\app.py", line 110, in on_thumbnail_click
    text_label_of_thumbnail = self.grid_layout.itemAtPosition(index, 0)\
AttributeError: 'NoneType' object has no attribute 'itemAt'
```

Seems something is missing in relation to the Thumbnail setup code but I'm too new at python to know what to do to fix it (and my google skills haven't shown me easy to follow fixes)

My code is available at https://github.com/photodude/Python-Desktop-App

**Comment by photodude** [comment]
Looks like the issue is the code requires images in the `my-album` folder
not sure how to make the code more robust to deal with the case that there are no images in the  `my-album` folder. Some conditional check for an empty  `my-album` folder would be needed to fix the issue.
